import type { Metadata } from "next";
import { Inter,} from "next/font/google";
import "./globals.css";

import "@fortawesome/fontawesome-free/css/all.min.css";
import Footer from "../lib/components/footer/footer";
const getstInter = Inter({
  subsets:["latin"],
})

export const metadata: Metadata = {
  title: "AI Chatbox",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {                
  return (
    <html lang="en" className={getstInter.className}>
      <body
        className={`antialiased`}
      >
        {children}
        <Footer/>
      </body>
    </html>
  );
}
